
################################################################################
# This script converts the count tables that are generated by umi tools
# Original format is long list with gene, cell, count in a long list.
# but I want a table which is gene (rows) x cells (columns), with counts as values.
#
# Also, I'd like to add the gene names.

library(reshape2)
library(stringr)

################################################################################

# Directories
if (exists('LOCAL')) {
    script_dir = '/Users/m.wehrens/Documents/git_repos/SCS_More_analyses/'
    base_dir = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_HPC_analysis.3b/'
    
    # 1. Rooij, 2. Hu
    #data_dir1 = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_UmiTools_CountTables_Wang_HCMSCS/ROOIJ/'
    #data_dir2 = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_UmiTools_CountTables_Wang_HCMSCS/HU/'
    data_dir1 = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_UmiTools_CountTables_Wang_HCMSCS/exclMulti_Filtered/ROOIJ/'
    data_dir2 = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_UmiTools_CountTables_Wang_HCMSCS/exclMulti_Filtered/HU/'
    
    
    #data_dir1 = NULL
    #data_dir2 = '/Users/m.wehrens/Data/_2019_02_HCM_SCS/2021_Wang_Counttables/'
    
    
} else {
    script_dir = '/hpc/hub_oudenaarden/mwehrens/scripts/SCS_HCM_analysis/'
    base_dir = '/hpc/hub_oudenaarden/mwehrens/data/HCM_SCS_RHL.2/'
    
    # 1. Rooij, 2. Hu
    data_dir1 = '/hpc/hub_oudenaarden/mwehrens/fastq/HCM_SCS/mapping.93.may25/'
    data_dir2 = '/hpc/hub_oudenaarden/mwehrens/fastq/WANG4/mapping/'
    
    #data_dir1='/hpc/hub_oudenaarden/mwehrens/fastq/HCM_SCS/mapping.93.may25/counttables/'
    #data_dir2='/hpc/hub_oudenaarden/mwehrens/fastq/WANG4/mapping/counttables/'
}

################################################################################
# 

HCM_SCS_ids = 
    c(  JE10='HUB-JE-010_HGVN3BGX9_S1_cat', 
        AL01='HUB-AL-s001_HG25TBGXF_S5_cat', 
        AL02='HUB-AL-s002_HG25TBGXF_S6_cat', 
        JE11='HUB-JE-011_HGVN3BGX9_S2_cat', 
        JE01='rJE1_AHFL7NBGX5_S3_cat', 
        JE02='JE2_AHY3WGBGX3_S1_cat', 
        JE03='JE4_AHFL7NBGX5_S4_cat', 
        JE04='JE3_AHY3WGBGX3_S2_cat', 
        JE05='JE5_AHFL77BGX5_S6_cat', 
        JE06='JE6_AHFL77BGX5_S7_cat', 
        JE07='JE7_AHFL7NBGX5_S16_cat', 
        JE08='JE8_AHFL7NBGX5_S17_cat', 
        MW05='HUB-MW-005_AH32W2BGX9_S5_cat', 
        MW06='HUB-MW-006_AH32W2BGX9_S6_cat', 
        MW07='HUB-MW-007_HC3GFBGX9_S6_cat', 
        MW08='HUB-MW-008_HC3GFBGX9_S7_cat')
dataset_list_paths_HCM = paste0(data_dir1, HCM_SCS_ids, '_pT.nonRibo_E99_Aligned.out.counts.tsv')
names(dataset_list_paths_HCM) = names(HCM_SCS_ids)

WANG_ids = c(   N1.97474.a = 'p.N1.plate.97474.part.1_cat',
                N1.97474.b = 'p.N1.plate.97474.part.2_cat',
    
                N2.97452.a = 'p.N2.plate.97452.part.1_cat',
                N2.97452.b = 'p.N2.plate.97452.part.2_cat',
                N2.97493.a = 'p.N2.plate.97493.part.1_cat',
                N2.97493.b = 'p.N2.plate.97493.part.2_cat',
    
                N3.97438.a = 'p.N3.plate.97438.part.1_cat',
                N3.97438.b = 'p.N3.plate.97438.part.2_cat',
    
                N4.97461.a = 'p.N4.plate.97461.part.1_cat',
                N4.97461.b = 'p.N4.plate.97461.part.2_cat',
    
                N5.97458.a = 'p.N5.plate.97458.part.1_cat',
                N5.97458.b = 'p.N5.plate.97458.part.2_cat',
    
                N13.100355.a = 'p.N13.plate.100355.part.1_cat',
                N13.100355.b = 'p.N13.plate.100355.part.2_cat',
    
                N14.104720.a = 'p.N14.plate.104720.part.1_cat',
                N14.104720.b = 'p.N14.plate.104720.part.2_cat')
# Annotation to patients
WANG_conversion_patients = sapply(str_split(WANG_ids, pattern = '\\.'), function(x) {x[[2]]})
names(WANG_conversion_patients) = names(WANG_ids)
# Annotation to samples
WANG_conversion_samples = sapply(str_split(WANG_ids, pattern = '\\.'), function(x) {x[[4]]})
names(WANG_conversion_samples) = names(WANG_ids)
# Generate full data paths
dataset_list_paths_WANG = paste0(data_dir2, WANG_ids, '_nc.nonRibo_E99_Aligned.out.counts.tsv')
# head_p.N1.plate.97474.part.1_cat_nc.nonRibo_E99_Aligned.out.counts.tsv.gz
names(dataset_list_paths_WANG) = names(WANG_ids)

dataset_list_paths=c(dataset_list_paths_HCM,dataset_list_paths_WANG)
dataset_source=c(rep('Rooij',length(dataset_list_paths_HCM)), rep('Hu',length(dataset_list_paths_WANG)))

################################################################################
# Obtain gene symbols with ensemble IDs
        
if (file.exists(paste0(base_dir,'Rdata/ens_to_sym_conv_table__93_v2.Rdata'))) {
    
    # Load the table if it was created and saved before
    print('Loading existing ens->name conversion table.')
    load(paste0(base_dir,'Rdata/ens_to_sym_conv_table__93_v2.Rdata'))
    
} else {
    
    stop('Conversion table ensembl ID and symbol not found.')
    
}

# Note: very few names are double, see 
# freq_names=table(names(ens_to_sym_conv_table__XX_v2))
# freq_names[freq_names>1]
# ens_to_sym_conv_table__XX_v2[names(ens_to_sym_conv_table__XX_v2) %in% names(freq_names[freq_names>1])]
# Seems to be mostly inconsequential genes
# ENSG00000276085 ENSG00000276085 ENSG00000277796 ENSG00000277796 ENSG00000230417 ENSG00000230417 ENSG00000277768 ENSG00000277768 ENSG00000277336 ENSG00000277336 
#        "CCL3L3"        "CCL3L1"        "CCL3L3"        "CCL3L1"     "LINC00856"     "LINC00595"        "CCL3L3"        "CCL3L1"        "CCL3L3"        "CCL3L1" 
# ENSG00000276700 ENSG00000276700 ENSG00000276700 ENSG00000276700 ENSG00000277739 ENSG00000277739 ENSG00000277739 ENSG00000277739 ENSG00000275757 ENSG00000275757 
#     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3" 
# ENSG00000275757 ENSG00000275757 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000274917 ENSG00000273730 ENSG00000273730 ENSG00000273730 
#     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN5"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2" 
# ENSG00000273730 ENSG00000207062 ENSG00000207062 ENSG00000206785 ENSG00000206785 ENSG00000278233 ENSG00000278233 ENSG00000278233 ENSG00000278233 ENSG00000275215 
#     "RNA5-8SN1"    "SNORA15B-2"    "SNORA15B-1"    "SNORA15B-2"    "SNORA15B-1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4" 
# ENSG00000275215 ENSG00000275215 ENSG00000275215 ENSG00000278189 ENSG00000278189 ENSG00000278189 ENSG00000278189 ENSG00000283889 ENSG00000283889 
#     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"     "RNA5-8SN4"     "RNA5-8SN3"     "RNA5-8SN2"     "RNA5-8SN1"       "KIR3DS1"      "KIR2DL5A" 


#rownames(dataTable1_df)
#ens_to_sym_conv_table__XX_v2[rownames(dataTable1_df)]
# show how many gene symbols are redundant
#length(unique(ens_to_sym_conv_table__XX_v2[unique(dataTable1$gene)]))/length(unique(dataTable1$gene))

################################################################################
# Conversion

for (idx in 1:length(dataset_list_paths)) {
    
    current_path = dataset_list_paths[idx]
    current_source = dataset_source[idx]
    
    # current_path =  dataset_list_paths[1]

    # Load the table
    current_data_table=NA; current_data_df=NA # just to prevent mix-ups
    current_data_table=
        read.table(current_path, header = 1)
    current_data_table=current_data_table[order(current_data_table$cell),]
    
    # Convert to gene x cell matrix (data frame)
    current_data_df=
        acast(current_data_table, gene~cell, value.var="count")
    current_data_df[is.na(current_data_df)]=0
    
    # Update rownames and colnames
    # Add gene name to ensembl ID
    rownames(current_data_df)=paste0(rownames(current_data_df),'_',ens_to_sym_conv_table__XX_v2[rownames(current_data_df)])
    # For our data, add leading X and 0s to cell names
    if (current_source == 'Rooij') {
        colnames(current_data_df)=paste0('X',sprintf("%03d", as.numeric(colnames(current_data_df))))
    }
    
    # Write the table
    write.table(x = current_data_df,file = gsub(pattern = 'counts.tsv', replacement = 'counts.table.tsv', x = current_path), row.names = T, col.names = T, quote = F)
    
}




